apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ipa2025-msapp-worker-showip
  namespace: devops-tools
spec:
  project: ipa-2025
  source:
    repoURL: 'https://github.com/MAK1z/Cisco123--IPA2025'
    targetRevision: HEAD
    path: worker/manifests/worker-showip
  destination:
    server: https://kubernetes.default.svc
    namespace: ipa-2025
  syncPolicy:
    automated:
      prune: true
      selfHeal: true